config/routes.rb
Rails.application.routes.draw do
  root :to => 'product_configrations#index'
  mount ShopifyApp::Engine, at: '/'
  resources :product_configrations do
  	collection do
  		get :get_product_detail
  	end
  end
  resources :app_configrations, :except => [:edit, :update, :destroy, :show, :new, :create]
  resources :home, :except => [:edit, :update, :destroy, :show, :new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product_configration.rb
class ProductConfigration < ApplicationRecord

	def options_value
		option_array = []
		if self.option_count.to_i == 1
			option_array << self.option1
		elsif self.option_count.to_i == 2
			option_array << self.option1
			option_array << self.option2
		elsif self.option_count.to_i == 3
			option_array << self.option1
			option_array << self.option2
			option_array << self.option3
		elsif self.option_count.to_i == 4
			option_array << self.option1
			option_array << self.option2
			option_array << self.option3
			option_array << self.option4
		elsif self.option_count.to_i == 5
			option_array << self.option1
			option_array << self.option2
			option_array << self.option3
			option_array << self.option4
			option_array << self.option5
		elsif self.option_count.to_i == 6
			option_array << self.option1
			option_array << self.option2
			option_array << self.option3
			option_array << self.option4
			option_array << self.option5
			option_array << self.option6
		elsif self.option_count.to_i == 7
			option_array << self.option1
			option_array << self.option2
			option_array << self.option3
			option_array << self.option4
			option_array << self.option5
			option_array << self.option6
			option_array << self.option7
		elsif self.option_count.to_i == 8
			option_array << self.option1
			option_array << self.option2
			option_array << self.option3
			option_array << self.option4
			option_array << self.option5
			option_array << self.option6
			option_array << self.option7
			option_array << self.option8
		elsif self.option_count.to_i == 9
			option_array << self.option1
			option_array << self.option2
			option_array << self.option3
			option_array << self.option4
			option_array << self.option5
			option_array << self.option6
			option_array << self.option7
			option_array << self.option8
			option_array << self.option9
		elsif self.option_count.to_i == 10
			option_array << self.option1
			option_array << self.option2
			option_array << self.option3
			option_array << self.option4
			option_array << self.option5
			option_array << self.option6
			option_array << self.option7
			option_array << self.option8
			option_array << self.option9
			option_array << self.option10
		end
		return option_array
	end

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::Shop
  include ShopifyApp::SessionStorage
end

app/controllers/app_configrations_controller.rb
class AppConfigrationsController < ApplicationController

	def index
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception
  skip_before_filter :verify_authenticity_token 
  #before_filter :current_shop

  private
  helper_method :current_shop

  def current_shop
    @current_shops = Shop.where(:shopify_domain => params[:shop])
    if @current_shops.count == 1
    	@current_shop = @current_shop.first.shopify_domain
    else
    	@current_shop = 'test_shop'
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ShopifyApp::AuthenticatedController
  
  def index
  	if params[:shop].present?
  		shop = params[:shop]
    	redirect_to("https://#{shop}/admin")
    else
			redirect_to("https://www.google.com")
  	end
  end

end

app/controllers/product_configrations_controller.rb
class ProductConfigrationsController < ApplicationController
  before_action :set_product_configration, only: [:show, :edit, :update, :destroy]

  def index
    # if params[:shop].present?
    #   @product_configrations = ProductConfigration.where(:shop_name => params[:shop]).order('id ASC')
    # else
    #   redirect_to "https://www.google.com"
    # end
    @product_configrations = ProductConfigration.where(:shop_name => params[:shop]).order('id ASC')
  end

  def show
  end

  def new
    @product_configration = ProductConfigration.new
    @product_configration.option_count = 0
  end

  def edit
  end

  def create
    @product_configration = ProductConfigration.new(product_configration_params)
    if @product_configration.save
      redirect_to product_configrations_path(:shop => @product_configration.shop_name)
    else
      render :new
    end
  end

  def update
    if @product_configration.update(product_configration_params)
      redirect_to product_configrations_path(:shop => @product_configration.shop_name)
    else
      render :edit
    end
  end

  def get_product_detail
    product_configrations = ProductConfigration.where(:shop_name => params[:shop], :product_sku => params[:product_sku])
    # product_configrations = ProductConfigration.where(:shop_name => "", :product_sku => params[:product_sku])
    if product_configrations.count == 1
      @product_configration = product_configrations.first
      render status:200, template: 'product_configrations/get_product_detail.json.jbuilder'
    else
      render status:200, json: {:product_present => false}
    end
  end

  def destroy
    shop_name = @product_configration.shop_name
    @product_configration.destroy
    redirect_to product_configrations_path(:shop => shop_name)
  end

  private

  def set_product_configration
    @product_configration = ProductConfigration.find(params[:id])
  end

  def product_configration_params
    params.require(:product_configration).permit(:product_name, :product_sku, :option_count, :shop_name, :option1, :option2, :option3, :option4, :option5, :option6, :option7, :option8, :option9, :option10)
  end

end

app/helpers/app_configrations_helper.rb
module AppConfigrationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_configrations_helper.rb
module ProductConfigrationsHelper
end

app/views/app_configrations/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
     ShopifyApp.ready(function(){
       ShopifyApp.Bar.initialize({ title: "Application Configration Guide" });
     });
  </script>
<% end %>
<div style="margin-left:10px;">
	<div class="col-sm-12">
	  <h1>Application Configration Guide</h1>
	  <p>Replace your shopify store url with <b>"example.myshopify.com"</b> which is written in shop parameter section of ajax call</p>
	  <ul class="list-group">
		  <h3>Write this javascript Code at the end of your Product Detail Page</h3>
		  <li class="list-group-item">
		  	<%= "<script type='text/javascript'>
		  		$(document).ready(function(){
		  			$.ajax({ url: 'https://simplyvideo.alchemative.net/video_configrations/get_product_video?product_sku={{ product.title }}&shop=example.myshopify.com',
		        	datatype:'json',
		        	type: 'GET',
		        	success: function (result) {
			          if (result.video_present == true)
			          {
			         		$('a#custom-video').show();
			         	}
			         	else
			          {
			         		$('a#custom-video').hide();
			         	}
			         	$('.video-product').attr('src', result.video_link);
							}
		        });        
					});  
				</script>" %>
				</li>
				<li class="list-group-item">
				<%= "<script type='text/javascript'>
					$(document).ready(function(){
				    $('.video-image').click(function(){
				      $('.zoomWrapper').hide();
				    });
				    $('.video-image').click(function(){
				      $('.video-product').show();
				    });
				   	$('.image-link').click(function(){
				      $('.zoomWrapper').show();
				    });
				  	$('.image-link').click(function(){
				      $('.video-product').hide();
				    });
					});
				</script>" %>
		  </li>
		  <h3>Write this CSS Code at the end of your Product Detail Page</h3>
		  <li class="list-group-item">
		  	<%= "<style type='text/css'>.video-product{display:none;}</style>" %>
		  </li>
		  <h3>Write this HTML Code where image gallery list showing in your Product Detail Page</h3>
		  <li class="list-group-item">
		  	<%= "<li> <a id='custom-video' class='thumb-link video-image' >
					{{ 'play_icon_white.png' | asset_url | img_tag }}
				</a></li>" %>
		  </li>
		  <h3>Write this HTML Code where image container showing in your Product Detail Page</h3>
		  <li class="list-group-item"><%= "<video width='400' controls loop autoplay controlsList='nodownload' class='video-product'><source src='' type='video/mp4'></video>" %></li>
	  </ul>
	</div>
</div>

app/views/home/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: "Home",
        icon: "<%= asset_path('favicon.ico') %>"
      });
    });
  </script>
<% end %>

<h2>Products</h2>

<ul>
  <% @products.each do |product| %>
    <li><%= link_to product.title, "https://#{@shop_session.url}/admin/products/#{product.id}", target: "_top" %></li>
  <% end %>
</ul>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
<script type="text/javascript">
  var eventName = typeof(Turbolinks) !== 'undefined' ? 'page:change' : 'DOMContentLoaded';

  document.addEventListener(eventName, function() {
    <% if flash[:notice] %>
      ShopifyApp.flashNotice("<%= j flash[:notice].html_safe %>");
    <% end %>

    <% if flash[:error] %>
      ShopifyApp.flashError("<%= j flash[:error].html_safe %>");
    <% end %>
  });
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simply Product Add On</title>
    <link rel="icon" type="image/ico" href="product_add_on.png" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Simply Product Add On</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
          	<li class="product_configrations active"><%= link_to  "Product Customization", product_configrations_path(:shop => params[:shop]) %></li>
            <li class="app_configrations"><%#= link_to  "Configrations", app_configrations_path(:shop => params[:shop]) %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div style="margin-top: 6%;">
      <%= yield %>
    </div>
  </body>
</html>

<script type="text/javascript">
	$(function()
	{
		var path = window.location.pathname
		if (path == "/product_configrations") {
			$('.product_configrations').addClass('active')
		}
	});
</script>

<script type="text/javascript">
  $(function()
  {
    var path = window.location.pathname
    if (path == "/product_configrations") {
      $('.product_configrations').addClass('active')
      $('.app_configrations').removeClass('active')
    }
    else if (path == "/app_configrations") {
      $('.product_configrations').removeClass('active')
      $('.app_configrations').addClass('active')
    }
    else
    {
      $('.product_configrations').addClass('active')
      $('.app_configrations').removeClass('active')
    }
  });
</script>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>

    <script type="text/javascript">
      ShopifyApp.init({
        apiKey: "<%= ShopifyApp.configuration.api_key %>",
        shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
        debug: <%= Rails.env.development? ? 'true' : 'false' %>,
        forceRedirect: true
      });
    </script>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>

app/views/product_configrations/_form.html.erb
<%= form_for(product_configration) do |f| %>
  <% if product_configration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_configration.errors.count, "error") %> prohibited this product_configration from being saved:</h2>

      <ul>
      <% product_configration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-sm-12">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :product_name, "Product Name" %>
        <%= f.text_field :product_name, :class => 'form-control' %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :product_sku, "Product SKU" %>
        <%= f.text_field :product_sku, :class => 'form-control' %>
      </div>
    </div>
  </div>

  <div class="col-sm-12">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :option_count, "No of Option" %>
        <%= f.number_field :option_count, :class => 'form-control', :id => "option_count", max: 10, min:0 %>
      </div>
    </div>
  </div>

  <div class="col-sm-12" style="display:none;">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :shop_name %>
        <%= f.text_field :shop_name, :class => 'form-control', :value => params[:shop]  %>
      </div>
    </div>
  </div>
  
  <div class="col-sm-12">
    <div class="col-sm-6 option1" style="display:none;">
      <div class="form-group">
        <%= f.label :option1, "Option 1" %>
        <%= f.text_field :option1, :class => 'form-control' %>
      </div>
    </div>
    <div class="col-sm-6 option2" style="display:none;">
      <div class="form-group">
        <%= f.label :option2, "Option 2" %>
        <%= f.text_field :option2, :class => 'form-control' %>
      </div>
    </div>
  </div>

  <div class="col-sm-12">
    <div class="col-sm-6 option3"  style="display:none;">
      <div class="form-group">
        <%= f.label :option3, "Option 3" %>
        <%= f.text_field :option3, :class => 'form-control' %>
      </div>
    </div>
    <div class="col-sm-6 option4"  style="display:none;">
      <div class="form-group">
        <%= f.label :option4, "Option 4" %>
        <%= f.text_field :option4, :class => 'form-control' %>
      </div>
    </div>
  </div>

  <div class="col-sm-12">
    <div class="col-sm-6 option5"  style="display:none;">
      <div class="form-group">
        <%= f.label :option5, "Option 5" %>
        <%= f.text_field :option5, :class => 'form-control' %>
      </div>
    </div>
    <div class="col-sm-6 option6"  style="display:none;">
      <div class="form-group">
        <%= f.label :option6, "Option 6" %>
        <%= f.text_field :option6, :class => 'form-control' %>
      </div>
    </div>
  </div>

  <div class="col-sm-12">
    <div class="col-sm-6 option7"  style="display:none;">
      <div class="form-group">
        <%= f.label :option7, "Option 7" %>
        <%= f.text_field :option7, :class => 'form-control' %>
      </div>
    </div>
    <div class="col-sm-6 option8"  style="display:none;">
      <div class="form-group">
        <%= f.label :option8, "Option 8" %>
        <%= f.text_field :option8, :class => 'form-control' %>
      </div>
    </div>
  </div>

  <div class="col-sm-12">
    <div class="col-sm-6 option9"  style="display:none;">
      <div class="form-group">
        <%= f.label :option9, "Option 9" %>
        <%= f.text_field :option9, :class => 'form-control' %>
      </div>
    </div>
    <div class="col-sm-6 option10"  style="display:none;">
      <div class="form-group">
        <%= f.label :option10, "Option 10" %>
        <%= f.text_field :option10, :class => 'form-control' %>
      </div>
    </div>
  </div>

  <div class="col-sm-12">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.submit :class => "btn btn-primary", :value => "Save Customization" %>
      </div>
    </div>
  </div>
<% end %>


<script type="text/javascript">
  $('#option_count').on('change', function(e) {
    e.preventDefault();
    e.stopPropagation(); 
    if ($('#option_count').val() == '1')
    {
      $('.option1').show();
      $('.option2').hide();
      $('.option3').hide();
      $('.option4').hide();
      $('.option5').hide();
      $('.option6').hide();
      $('.option7').hide();
      $('.option8').hide();
      $('.option9').hide();
      $('.option10').hide();
    }

    else if ($('#option_count').val() == '2')
    {
      $('.option1').show();
      $('.option2').show();
      $('.option3').hide();
      $('.option4').hide();
      $('.option5').hide();
      $('.option6').hide();
      $('.option7').hide();
      $('.option8').hide();
      $('.option9').hide();
      $('.option10').hide();
    }

    else if ($('#option_count').val() == '3')
    {
      $('.option1').show();
      $('.option2').show();
      $('.option3').show();
      $('.option4').hide();
      $('.option5').hide();
      $('.option6').hide();
      $('.option7').hide();
      $('.option8').hide();
      $('.option9').hide();
      $('.option10').hide();
    }

    else if ($('#option_count').val() == '4')
    {
      $('.option1').show();
      $('.option2').show();
      $('.option3').show();
      $('.option4').show();
      $('.option5').hide();
      $('.option6').hide();
      $('.option7').hide();
      $('.option8').hide();
      $('.option9').hide();
      $('.option10').hide();
    }

    else if ($('#option_count').val() == '5')
    {
      $('.option1').show();
      $('.option2').show();
      $('.option3').show();
      $('.option4').show();
      $('.option5').show();
      $('.option6').hide();
      $('.option7').hide();
      $('.option8').hide();
      $('.option9').hide();
      $('.option10').hide();
    }

    else if ($('#option_count').val() == '6')
    {
      $('.option1').show();
      $('.option2').show();
      $('.option3').show();
      $('.option4').show();
      $('.option5').show();
      $('.option6').show();
      $('.option7').hide();
      $('.option8').hide();
      $('.option9').hide();
      $('.option10').hide();
    }

    else if ($('#option_count').val() == '7')
    {
      $('.option1').show();
      $('.option2').show();
      $('.option3').show();
      $('.option4').show();
      $('.option5').show();
      $('.option6').show();
      $('.option7').show();
      $('.option8').hide();
      $('.option9').hide();
      $('.option10').hide();
    }

    else if ($('#option_count').val() == '8')
    {
      $('.option1').show();
      $('.option2').show();
      $('.option3').show();
      $('.option4').show();
      $('.option5').show();
      $('.option6').show();
      $('.option7').show();
      $('.option8').show();
      $('.option9').hide();
      $('.option10').hide();
    }

    else if ($('#option_count').val() == '9')
    {
      $('.option1').show();
      $('.option2').show();
      $('.option3').show();
      $('.option4').show();
      $('.option5').show();
      $('.option6').show();
      $('.option7').show();
      $('.option8').show();
      $('.option9').show();
      $('.option10').hide();
    }

    else if ($('#option_count').val() == '10')
    {
      $('.option1').show();
      $('.option2').show();
      $('.option3').show();
      $('.option4').show();
      $('.option5').show();
      $('.option6').show();
      $('.option7').show();
      $('.option8').show();
      $('.option9').show();
      $('.option10').show();
    }

    else
    {
      $('.option1').hide();
      $('.option2').hide();
      $('.option3').hide();
      $('.option4').hide();
      $('.option5').hide();
      $('.option6').hide();
      $('.option7').hide();
      $('.option8').hide();
      $('.option9').hide();
      $('.option10').hide();
    };

  });
</script>

app/views/product_configrations/edit.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
     ShopifyApp.ready(function(){
       ShopifyApp.Bar.initialize({ title: "Product Customization" });
     });
  </script>
<% end %>
<h1>Editing Product Configration</h1>

<%= render 'form', product_configration: @product_configration %>

<%= link_to 'Show', @product_configration %> |
<%= link_to 'Back', product_configrations_path %>

app/views/product_configrations/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
     ShopifyApp.ready(function(){
       ShopifyApp.Bar.initialize({ title: "Product Customization" });
     });
  </script>
<% end %>
<div style="margin-left:20px;">
  <%= link_to 'New Customization', new_product_configration_path(:shop => params[:shop]), :class => "btn btn-primary" %>  
</div>

<div class="col-sm-12">
  <h2 class="text-center">Product Customization</h2>
  <div class="table-responsive">
    <table class="table table-condensed table-hover">
      <thead>
        <tr>
          <th class="col-sm-3">Product Name</th>
          <th class="col-sm-3">Product SKU</th>
          <th class="col-sm-3">No of Options</th>
          <th class="col-sm-3">Action</th>
        </tr>
      </thead>
      <tbody>
        <% if @product_configrations.count > 0 %>
          <% @product_configrations.each do |product_configration| %>
            <tr>
              <td class="col-sm-3"><%= product_configration.product_name %></td>
              <td class="col-sm-3"><%= product_configration.product_sku %></td>
              <td class="col-sm-3"><%= product_configration.option_count %></td>
              <td class="col-sm-3"><%= link_to 'Delete', product_configration, method: :delete, :class => "btn btn-danger" %></td>
            </tr>
          <% end %>
        <% else %>
          <td colspan="4" class="text-center"> No History Found </td>
        <% end %>
      </tbody>
    </table>
  </div>

  <br>

</div>

app/views/product_configrations/new.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
     ShopifyApp.ready(function(){
       ShopifyApp.Bar.initialize({ title: "Product Customization" });
     });
  </script>
<% end %>
<h2 class="text-center">New Product Customization</h3>

<%= render 'form', product_configration: @product_configration %>

app/views/product_configrations/show.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
     ShopifyApp.ready(function(){
       ShopifyApp.Bar.initialize({ title: "Product Customization" });
     });
  </script>
<% end %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @product_configration.product_name %>
</p>

<p>
  <strong>Product sku:</strong>
  <%= @product_configration.product_sku %>
</p>

<p>
  <strong>Option count:</strong>
  <%= @product_configration.option_count %>
</p>

<p>
  <strong>Shop name:</strong>
  <%= @product_configration.shop_name %>
</p>

<p>
  <strong>Option1:</strong>
  <%= @product_configration.option1 %>
</p>

<p>
  <strong>Option2:</strong>
  <%= @product_configration.option2 %>
</p>

<p>
  <strong>Option3:</strong>
  <%= @product_configration.option3 %>
</p>

<p>
  <strong>Option4:</strong>
  <%= @product_configration.option4 %>
</p>

<p>
  <strong>Option5:</strong>
  <%= @product_configration.option5 %>
</p>

<p>
  <strong>Option6:</strong>
  <%= @product_configration.option6 %>
</p>

<p>
  <strong>Option7:</strong>
  <%= @product_configration.option7 %>
</p>

<p>
  <strong>Option8:</strong>
  <%= @product_configration.option8 %>
</p>

<p>
  <strong>Option9:</strong>
  <%= @product_configration.option9 %>
</p>

<p>
  <strong>Option10:</strong>
  <%= @product_configration.option10 %>
</p>

<%= link_to 'Edit', edit_product_configration_path(@product_configration) %> |
<%= link_to 'Back', product_configrations_path %>